# **Matrices 2: Matrix Inverses**
---

In your maths workshops you saw how to do matrix multiplication, addition and subtraction. However, we haven't talked about how to divide matrices by other matrices. This is more complicated than multiplying matrices together. In fact, we don't usually talk about dividing by a matrix at all; instead, we talk about **multiplying by its inverse**. In this workshop we will learn how calculate the inverse of a $2\times2$ matrix by hand, then calculate the inverse of larger matrices using Python, and then look at a specific application of inverse matrices: solving simultaneous equations.

## **Part 1: Inverting $2 \times 2$ Matrices**
---
In this part of the workshop we will learn:
- what an inverse matrix is
- what a determinant is
- how to invert a $2 \times 2$ matrix by hand

### The Inverse Matrix and Determinant

The inverse of a square matrix $\textbf{A}$ is another matrix, written as $\textbf{A}^{-1}$, where

$$\textbf{A} \textbf{A}^{-1} = \textbf{A}^{-1} \textbf{A} = \textbf{E}$$

This means that the inverse of a matrix is defined as the matrix which, when multiplied by the original matrix, produces the identity matrix $\textbf{E}$. This is similar to dividing - multiplying a number by its "inverse" (i.e. one divided by that number) is the same as dividing by that number, and always gives an answer of 1. In terms of the coordinate transformations we talked about last week, an inverse matrix will undo a coordinate transformation.

It is only possible to define the inverse of a matrix $\textbf{A}$ if a quantity known as the determinant of the matrix (written as $\textrm{det } \textbf{A}$ or $|\textbf{A}|$) is non-zero. If $\textrm{det } \textbf{A} = 0$, then $\textbf{A}$ is said to be "singular" and $\textbf{A}^{-1}$ does not exist.

**Very roughly**, in terms of the coordinate transformation we saw last week, a determinant tells you how much the area of a shape will change when apply a coordinate transformation. For example, a rotation matrix $\left( \begin{array}{cc} 0 & -1 \\ 1 & 0 \end{array} \right)$ won't change the area at all, but a matrix which stretches in the $x$ and $y$ dimensions $\left( \begin{array}{cc} 2 & 0 \\ 0 & 2 \end{array} \right)$ will change the area of a shape by a factor of 4. If the determinant is zero, the shape disappears entirely as its area becomes 0, and it's not possible to undo that - there is no inverse. If you're interested, I highly recommend [this video](https://www.youtube.com/watch?v=Ip3X9LOh2dk).

### The Inverse and Determinant of a $2 \times 2$ matrix.

For small matrices, we can work out their determinant and inverse by hand. Any $2 \times 2$ matrix can be written as

$$\textbf{A} = \bigg( \begin{array}{cc} a & b \\ c & d \end{array} \bigg)$$

The determinant of this matrix is defined as
$$\textrm{det } \textbf{A} = ad-bc.$$
The inverse matrix is then defined as
$$\textbf{A}^{-1} = \frac{1}{\textrm{det } \textbf{A}} \bigg( \begin{array}{cc} d & -b \\ -c & a \end{array} \bigg).$$

Using these formulae we can write down the inverse of any $2 \times 2$ matrix.

### Simultaneous Equations

A really important use of inverse matrices is solving simultaneous equations. If we have two pairs of equations
$$a_{11}x_1 + a_{12}x_2 = b_1$$
$$a_{21}x_1 + a_{22}x_2 = b_2;$$
these can be rewritten as a matrix equation (multiply this out if you'd like to check):
$$\bigg( \begin{array}{cc} a_{11} & a_{12} \\ a_{21} & a_{22} \end{array} \bigg)\bigg( \begin{array}{c} x_{1} \\ x_{2} \end{array} \bigg) = \bigg( \begin{array}{c} b_{1} \\ b_{2} \end{array} \bigg)$$
or
$$ \textbf{A}\textbf{x} = \textbf{b}.$$
To solve this equation we need to find $\textbf{x}$. We can do this by multiplying both sides by the inverse of $\textbf{A}$:
$$ \textbf{A}^{-1}\textbf{A}\textbf{x} = \textbf{A}^{-1}\textbf{b}.$$
Since $\textbf{A}^{-1}\textbf{A} = \textbf{E}$, and the identity matrix times any vector does change it ($\textbf{E}\textbf{x}=\textbf{x}$), this simplifies to
$$\textbf{x} = \textbf{A}^{-1}\textbf{b}.$$
Therefore if we can calculate the inverse of $\textbf{A}$, we can find $\textbf{x}$ and solve the equations.

### <font color='#3366CC'>Exercises

<font color='#3366CC'>(This is Question 7.16 in the Maths Question Booklets.)

<font color='#3366CC'>**Exercise 1:** Calculate the inverse of each of the following matrices.

<font color='#3366CC'>a) $\textbf{A} = \bigg( \begin{array}{cc} 8 & -5 \\ -3 & 2 \end{array} \bigg)$

<font color='#3366CC'>b) $\textbf{B} = \bigg( \begin{array}{cc} 3 & 1 \\ -1 & 3 \end{array} \bigg)$

<font color='#3366CC'>c) $\textbf{C} = \bigg( \begin{array}{cc} 5 & 16 \\ -1 & -3 \end{array} \bigg)$

<!--  <font color='#3366CC'> d) $\textbf{D} = \bigg( \begin{array}{cc} 9 & -2 \\ 10 & -2 \end{array} \bigg)$ -->

<font color='#3366CC'>(These three exercises are Question 7.17 in the Maths Question Booklets.)

<font color='#3366CC'>**Exercise 2:** Convert the following simultaneous equations into matrix form.
$$2x_1 + 4x_2 = 2$$
$$-3x_1 + x_2 = 11$$

<font color='#3366CC'>**Exercise 3:** Calculate the inverse of the matrix you obtain from Exercise 2.

<font color='#3366CC'>**Exercise 4:** Use the inverse matrix you calculate in Exercise 3 to calculate $x_1$ and $x_2$.

### A Chemical Example

The Arrhenius equation states how the rate of a reaction depends on temperature:
$$k=Ae^{-E_a/RT}.$$

If we take the natural logarithm of both sides we get a linear equation:
$$\ln{k} = \ln{A}- \frac{E_a}{RT}.$$

If we calculate the rate of reaction at two different temperatures, we can write two simultaneous equations which have two unknowns: $\ln{A}$ and $E_a$. For example, if a reaction takes place at $4.75 \times 10^{-4}$ s$^{-1}$ at 293 K and $5.48 \times 10^{-2}$ s$^{-1}$ at 333 K, then

$$\ln{(4.75 \times 10^{-4})} = \ln{A}- \frac{E_a}{8.314\times 293 \textrm{ J}}$$
and
$$\ln{(5.48 \times 10^{-2})} = \ln{A}- \frac{E_a}{8.314\times 333 \textrm{ J}}.$$

Simplifying these produces:

$$-7.652 = \ln{A}-(4.105 \times 10^{-4} \textrm{ J}^{-1}) E_a$$
$$-2.904 = \ln{A}-(3.612 \times 10^{-4} \textrm{ J}^{-1}) E_a$$


<font color='#3366CC'>**Exercise 1:** Write these two equations in matrix form.

<font color='#3366CC'>**Exercise 2:** Calculate the inverse of the matrix you defined in Exercise 1.

<font color='#3366CC'>**Exercise 3:** Use the inverse matrix to calculate $\ln{A}$ and $E_a$.

## **Part 2: Inverting Larger Matrices**
---
In this part of the workshop we will learn:
- how to use Python to calculate an inverse matrix
- how to use Python to calculate a determinant
- how to solve linear equations using Python

It is possible to calculate the inverse of larger matrices by hand - [here's a guide for $3\times3$ matrices](https://www.wikihow.com/Find-the-Inverse-of-a-3x3-Matrix) and [one for $4\times4$ matrices](https://semath.info/src/inverse-cofactor-ex4.html) if you're interested. However, as you can see from those guides it's a real pain, and in practice very few people calculate inverse matrices by hand. It's far quicker to get computers to do it, so that's what we'll do in this workshop.

### Starting Small

Before we get on to larger matrices, we will learn how to use `numpy` tools to solve some of the problems we did by hand earlier. The first question asked you to invert the matrix $\textbf{A} = \bigg( \begin{array}{cc} 8 & -5 \\ -3 & 2 \end{array} \bigg)$. First we need to define that using Python.

In [ ]:
import numpy as np
np.set_printoptions(5)

In [9]:
A = np.array([[8,-5],[-3,2]])
print(A)

[[ 8 -5]
 [-3  2]]


Having done that, we can use use `numpy` functions to calculate the determinant ([`numpy.linalg.det`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)) and the inverse ([`numpy.linalg.inv`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)). This come from the `linalg` (LINear ALGebra) subsection of `numpy`, but work in the same way as any function from numpy.

In [10]:
detA = np.linalg.det(A)
print('det A =',detA)

invA = np.linalg.inv(A)
print('Inverse of A:')
print(invA)

det A = 1.0
Inverse of A:
[[2. 5.]
 [3. 8.]]


Hopefully this is the same answer you got earlier!

### Tackling Larger Matrices

We can use the exact same function to find the inverses of larger matrices. The code below will create a random $n\times n$ matrix, calculate it's determinant, and if the determinant is not zero calculate the inverse matrix.

In [12]:
n = 8

A = np.random.random((n,n))
print(A)
detA = np.linalg.det(A)
print('det A =',detA)
if detA != 0:
  invA = np.linalg.inv(A)
  print('Inverse of A:')
  print(invA)
  print('Check: A*invA =')
  print(np.round(np.matmul(A,invA),1))

[[0.77326 0.6066  0.16614 0.98973 0.63868 0.69372 0.47474 0.76367]
 [0.49687 0.16457 0.23562 0.09615 0.10179 0.70507 0.52467 0.51422]
 [0.83113 0.57683 0.39662 0.24084 0.0799  0.62269 0.75038 0.12742]
 [0.35097 0.98419 0.29488 0.2713  0.98976 0.5059  0.89386 0.93544]
 [0.90742 0.75436 0.1075  0.86213 0.91786 0.88081 0.40417 0.18752]
 [0.06622 0.85832 0.04994 0.04855 0.29889 0.11673 0.28018 0.14524]
 [0.68847 0.18889 0.1105  0.9295  0.36395 0.24828 0.45743 0.1126 ]
 [0.32833 0.46029 0.36769 0.88416 0.43425 0.54265 0.07889 0.90025]]
det A = 0.011053272031031451
Inverse of A:
[[ 6.30224 -5.51445  4.04222  0.62838 -0.66711 -4.14243 -4.59609 -2.03923]
 [ 0.7477  -0.5194   0.40286 -0.44774 -0.19261  1.28928 -0.58149 -0.02452]
 [-2.63835 -1.84189  2.13033  1.00776  0.436   -1.87227 -0.22765  2.18116]
 [-2.43959  2.32955 -1.90156 -0.78589  0.06124  2.16826  2.94415  1.0938 ]
 [-0.16339 -1.60586  0.38878  1.29124  0.95812 -1.91375 -0.80115 -0.13152]
 [-3.61693  4.4844  -2.56411 -1.06707  1.2552

### <font color='#3366CC'>Exercises

<font color='#3366CC'>**Exercise 1:** Define a variable which contains the matrix $\textbf{B} = \bigg( \begin{array}{cc} 3 & 1 \\ -1 & 3 \end{array} \bigg)$, and use `numpy` to calculate its determinant and inverse. Check that this answer matches the one you got by hand.

<font color='#3366CC'>**Exercise 2:** Use `numpy` to solve the following simultaneous equations. Check that the answer you get matches the one you got earlier.
$$2x_1 + 4x_2 = 2$$
$$-3x_1 + x_2 = 11$$

<font color='#3366CC'>(Hint: if you're not sure how to tackle this, work through the same steps as when you solved this by hand earlier. Remember that you can use `numpy.matmul` function to multiply matrices and vectors together.)

<font color='#3366CC'>**Exercise 3:** Define a variable which contains the matrix $\textbf{C} = \left( \begin{array}{cccc} 5 & 1 & 1 & 2 \\ -1 & 3 & 9 & -2 \\ 4 & 4 & -7 & 0 \\ 8 & 0 & 2 & 0 \end{array} \right)$, and use `numpy` to calculate its determinant and inverse.

<font color='#3366CC'>**Exercise 4:** Use `numpy` to solve the following simultaneous equations.
$$2x_1 - 4x_2 = 2$$
$$-3x_1 + x_3 = 11$$
$$5x_1 + 2x_2 -3x_3 = 11$$
Check your answers by inserting them back into these simultaneous equations.

<font color='#3366CC'>**Optional Exercise 5:** There is a numpy function which can find the values of $\textbf{x}$ for the simultaneous equations above in a single step, instead of finding the inverse and then doing a matrix multiplication. See if you can find out what it is and write the code to do it below.

### A Chemical Example

In atmospheric and environmental chemistry, we want to uncover correlations between atmospheric conditions and the concentration of certain pollutants. The most common way to do this is to perform **multiple linear regression (MLR)**. In general, MLR is written as a series of simultaneous equations:
$$y_1 = \beta_1x_{11} + \beta_2x_{12} + \beta_3x_{13} + ...$$
$$y_2 = \beta_1x_{21} + \beta_2x_{22} + \beta_3x_{23} + ...$$
Here $y_{i}$ is the $i$th measurement of the variable we are trying to predict, $x_{ij}$ is the $i$th measurement of the $j$th variable which might be related to $y$, and $\beta_j$ is a coefficient we are trying to calculate which will tell us whether there is a relationship between $y$ and $x_j$.

We can write these equations as a matrix equation:
$$\textbf{y} = \textbf{X}\boldsymbol{\beta}$$
Here $\textbf{X}$ has the same number of rows as the number of measurements, and the same number of columns as the number of different variables. Normally, we have many more measurements than variables - many more rows than columns. In order to include all of this information and get the best possible estimates of
$\boldsymbol{\beta}$, we use a least squares method. This gives the following equation to calculate $\boldsymbol{\beta}$:
$$\boldsymbol{\beta} = (\textbf{X}^\top \textbf{X})^{-1} \textbf{X}^\top \textbf{y}.$$


In [this data file](https://raw.githubusercontent.com/alanmlewis/ProgrammingforChem/main/spain_air_quality.csv) are 21 measurements of air quality data and atmospheric conditions from different measuring stations around Spain. We are going to use this data to work out which of these help us predict the concentration of ozone.

<font color='#3366CC'>**Exercise 1:** Use the equations above to calculate the regression weights $\boldsymbol{\beta}$. Print these regression weights. Which variables are positively correlated with ozone concentrations and which are negatively correlated?

In [ ]:
# Load the numerical data from the file file
data = np.loadtxt('https://raw.githubusercontent.com/alanmlewis/ProgrammingforChem/main/spain_air_quality.csv',skiprows=1,usecols=range(1,8),delimiter=',')
# Seperate out the ozone concentration. This is our "target" variable y.
o3_conc = data[:,2]
y = o3_conc
# Put all the other data into a variable X for convenience.
# The columns of X describe, in order: NO conc., NO2 conc., Wind Direction (degrees), Wind speed (m/s), Temp. (ºC), Relative Humidity (%)
X = data[:,[0,1,3,4,5,6]]



<font color='#3366CC'>**Exercise 2:** Calculate the predicted values of $\textbf{y}$ using the regression weights $\boldsymbol{\beta}$ you calculated in Exercise 1. Use `matplotlib`'s `scatter` function to plot the real values of $\textbf{y}$ against the predicted values of $\textbf{y}$. (Google `matplotlib scatter` if you're not sure how to use this function!)

<font color='#3366CC'>**Exercise 3:** To work out which parameters are most important, we need to calculate the uncertainity in each parameter. This is given by the square root of the diagonal elements of the following matrix:
$$\textbf{V} = \sigma^2(\textbf{X}^\top\textbf{X})^{-1}.$$

<font color='#3366CC'>Use `numpy`'s `sqrt` and `diag` functions to calculate the square root of the diagonal elements of $\textbf{V}$; these are the uncertainties in $\boldsymbol{\beta}$. (To help you the code to calculate $\sigma^2$ is already written). Then divide each element of $\boldsymbol{\beta}$ by the corresponding uncertainty to work out which variables are most important. Which two variables are most important for predicting ozone concentration?

In [ ]:
# Set y_pred equal to you predicted y values from Exercise 2
y_pred =

# Calculate the scale factor sigma^2.
sigma_sq = np.sum(np.square(y_pred-o3_conc))/(21-6)
